apiVersion: apps/v1
kind: Deployment
metadata:
  name: availability-service
  labels:
    app: availability-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: availability-service
  template:
    metadata:
      labels:
        app: availability-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/runtimepath: /runtime_metrics
        prometheus.io/port: "80"
    spec:
      containers:
        - name: availability-service
          image: meho27/pacco.services.availability:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: availability-config
              mountPath: /app/appsettings.json
              subPath: appsettings.json
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: kube
      volumes:
        - name: availability-config
          configMap:
            name: availability-config