apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing-service
  labels:
    app: pricing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pricing-service
  template:
    metadata:
      labels:
        app: pricing-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/runtimepath: /runtime_metrics
        prometheus.io/port: "80"
    spec:
      containers:
        - name: pricing-service
          image: meho27/pacco.services.pricing:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: pricing-config
              mountPath: /app/appsettings.json
              subPath: appsettings.json
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: kube
      volumes:
        - name: pricing-config
          configMap:
            name: pricing-config