apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-maker-service
  labels:
    app: order-maker-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-maker-service
  template:
    metadata:
      labels:
        app: order-maker-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/runtimepath: /runtime_metrics
        prometheus.io/port: "80"
    spec:
      containers:
        - name: order-maker-service
          image: meho27/pacco.services.order-maker:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: order-maker-config
              mountPath: /app/appsettings.json
              subPath: appsettings.json
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: kube
      volumes:
        - name: order-maker-config
          configMap:
            name: order-maker-config