apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32120
    protocol: TCP
    name: http
  selector:
    app: api-gateway-service
