apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: api-gateway-service