apiVersion: v1
kind: Service
metadata:
  name: customers-service
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: customers-service